# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-31 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameboard', models.CharField(max_length=1024)),
                ('gameboard_rows', models.IntegerField(default=0)),
                ('gameboard_cols', models.IntegerField(default=0)),
            ],
        ),
    ]
