# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grids', '0005_auto_20161103_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homegoals', models.IntegerField(default=0)),
                ('awaygoals', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('max_time', models.IntegerField(default=90)),
                ('time_increment', models.IntegerField(default=5)),
                ('current_turn', models.CharField(choices=[('home', 'Home Team'), ('away', 'Away Team'), ('home_ai', 'Home Team (CPU)'), ('away_ai', 'Away Team (CPU)')], max_length=10)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grids.GameBoard')),
            ],
        ),
    ]
