# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grids', '0006_gamestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='current_turn',
            field=models.CharField(choices=[('home', 'Home Team'), ('away', 'Away Team'), ('home_ai', 'Home Team (CPU)'), ('away_ai', 'Away Team (CPU)')], default='home', max_length=10),
        ),
    ]
