# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grids', '0007_auto_20161106_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboard',
            name='gameboard',
            field=models.CharField(default="[['0', '0', '0', '0'], ['0', '0', '0', '0'], ['0', '0', '0', '0']]", max_length=1024),
        ),
    ]
