# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grids', '0008_auto_20161106_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboard',
            name='cols',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='gameboard',
            name='rows',
            field=models.IntegerField(default=3),
        ),
    ]
