# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grids', '0009_auto_20161106_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='player',
        ),
        migrations.AddField(
            model_name='position',
            name='player',
            field=models.ManyToManyField(to='grids.Player'),
        ),
    ]
