# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grids', '0010_auto_20161106_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('player', models.ManyToManyField(to='grids.Player')),
            ],
        ),
        migrations.AddField(
            model_name='gamestate',
            name='teams',
            field=models.ManyToManyField(to='grids.Team'),
        ),
    ]
