# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-29 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grids', '0012_auto_20170727_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='active_position',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='grids.Position'),
            preserve_default=False,
        ),
    ]
